server:
  port: ${server.port}

logging:
  level:
    root: info
    site.euan.bester: DEBUG

spring:
  config:
    import: classpath:application-secret.yml
  profile:
    active: secret
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  cache:
    redis:
      time-to-live: 28800000 #8小时
  datasource:
    url: jdbc:mysql://${database.host}:${database.port}/${database.tableName}
    username: ${database.username}
    password: ${database.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    mongodb:
      authentication-database: ${mongodb.authentication-database}
      username: ${mongodb.username}
      password: ${mongodb.password}
      host: ${mongodb.host}
      port: ${mongodb.port}
      database: ${mongodb.database}
  servlet:
    multipart:
      #最大上传大小
      max-file-size: 3MB
      #最大请求大小
      max-request-size: 10MB
      enabled: true
  messages:
    basename: messages
    encoding: UTF-8
  session:
    timeout: 30m
  redis:
    database: 0
    host: ${redis.host}
    port: ${redis.port}
    timeout: 5000
    lettuce:
      pool:
        max-active: 32
        max-wait: -1ms
        max-idle: 16
        min-idle: 8
    password: ${redis.password}
  mail:
    host: smtp.qq.com
    username: ${mail.username}
    password: ${mail.password}
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          ssl:
            enable: true
          auth: true
          starttls:
            enable: true
            required: true

# 腾讯云COS配置
tencent:
  cos:
    # 存储桶名称
    bucketName: euan-1306554881
    # 腾讯云API密钥ID
    secretId: ${tencent.cos.secretId}
    # 腾讯云API密钥
    secretKey: ${tencent.cos.secretKey}
    # 区域
    region: ap-chengdu
    # 文件夹
    folder: bester/